spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bank_accounts?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    listener:
      simple:
        auto-startup: false
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081
