version: '3.8'

services:
  mysql-customers:
    image: mysql:8.4
    container_name: mysql-customers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_customers
    ports:
      - "3307:3306"
    volumes:
      - db_data_customers:/var/lib/mysql

  mysql-accounts:
    image: mysql:8.4
    container_name: mysql-accounts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_accounts
    ports:
      - "3308:3306"
    volumes:
      - db_data_accounts:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  customers:
    build: ./customers
    container_name: customers
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-customers:3306/bank_customers?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8081"
    depends_on:
      - mysql-customers
      - rabbitmq

  accounts:
    build: ./accounts
    container_name: accounts
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-accounts:3306/bank_accounts?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8082
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      - mysql-accounts
      - rabbitmq

volumes:
  db_data_customers:
  db_data_accounts:
